// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: army.sql

package db

import (
	"context"
)

const getTroopCatalog = `-- name: GetTroopCatalog :many
SELECT troop_type, level_req, elixir_cost, hit_points, hit_rate, damage, speed, attack_range, housing_space, description FROM troops
`

func (q *Queries) GetTroopCatalog(ctx context.Context) ([]Troop, error) {
	rows, err := q.db.Query(ctx, getTroopCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Troop
	for rows.Next() {
		var i Troop
		if err := rows.Scan(
			&i.TroopType,
			&i.LevelReq,
			&i.ElixirCost,
			&i.HitPoints,
			&i.HitRate,
			&i.Damage,
			&i.Speed,
			&i.AttackRange,
			&i.HousingSpace,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
