// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPlayerAuth = `-- name: CreatePlayerAuth :one
INSERT INTO authorisation (player_id, username, password_hash)
VALUES ($1, $2, $3)
RETURNING player_id, username
`

type CreatePlayerAuthParams struct {
	PlayerID     uuid.UUID
	Username     string
	PasswordHash string
}

type CreatePlayerAuthRow struct {
	PlayerID uuid.UUID
	Username string
}

func (q *Queries) CreatePlayerAuth(ctx context.Context, arg CreatePlayerAuthParams) (CreatePlayerAuthRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayerAuth, arg.PlayerID, arg.Username, arg.PasswordHash)
	var i CreatePlayerAuthRow
	err := row.Scan(&i.PlayerID, &i.Username)
	return i, err
}

const createPlayerProfile = `-- name: CreatePlayerProfile :one
INSERT INTO player (id)
VALUES ($1)
RETURNING id, village_level, gold_coins, elixir
`

type CreatePlayerProfileRow struct {
	ID           uuid.UUID
	VillageLevel int32
	GoldCoins    int32
	Elixir       int32
}

func (q *Queries) CreatePlayerProfile(ctx context.Context, id uuid.UUID) (CreatePlayerProfileRow, error) {
	row := q.db.QueryRowContext(ctx, createPlayerProfile, id)
	var i CreatePlayerProfileRow
	err := row.Scan(
		&i.ID,
		&i.VillageLevel,
		&i.GoldCoins,
		&i.Elixir,
	)
	return i, err
}

const getAuthByUsername = `-- name: GetAuthByUsername :one
SELECT player_id, username, password_hash
FROM authorisation
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAuthByUsername(ctx context.Context, username string) (Authorisation, error) {
	row := q.db.QueryRowContext(ctx, getAuthByUsername, username)
	var i Authorisation
	err := row.Scan(&i.PlayerID, &i.Username, &i.PasswordHash)
	return i, err
}
