// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayerAuth = `-- name: CreatePlayerAuth :one
INSERT INTO authorisation (player_id, username, password_hash)
VALUES ($1, $2, $3)
RETURNING player_id, username
`

type CreatePlayerAuthParams struct {
	PlayerID     pgtype.UUID `json:"player_id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
}

type CreatePlayerAuthRow struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Username string      `json:"username"`
}

func (q *Queries) CreatePlayerAuth(ctx context.Context, arg CreatePlayerAuthParams) (CreatePlayerAuthRow, error) {
	row := q.db.QueryRow(ctx, createPlayerAuth, arg.PlayerID, arg.Username, arg.PasswordHash)
	var i CreatePlayerAuthRow
	err := row.Scan(&i.PlayerID, &i.Username)
	return i, err
}

const createPlayerProfile = `-- name: CreatePlayerProfile :one
INSERT INTO player (id)
VALUES ($1)
RETURNING id, village_level, gold_coins, elixir
`

type CreatePlayerProfileRow struct {
	ID           pgtype.UUID `json:"id"`
	VillageLevel int32       `json:"village_level"`
	GoldCoins    int32       `json:"gold_coins"`
	Elixir       int32       `json:"elixir"`
}

func (q *Queries) CreatePlayerProfile(ctx context.Context, id pgtype.UUID) (CreatePlayerProfileRow, error) {
	row := q.db.QueryRow(ctx, createPlayerProfile, id)
	var i CreatePlayerProfileRow
	err := row.Scan(
		&i.ID,
		&i.VillageLevel,
		&i.GoldCoins,
		&i.Elixir,
	)
	return i, err
}

const getAuthByUsername = `-- name: GetAuthByUsername :one
SELECT player_id, username, password_hash
FROM authorisation
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetAuthByUsername(ctx context.Context, username string) (Authorisation, error) {
	row := q.db.QueryRow(ctx, getAuthByUsername, username)
	var i Authorisation
	err := row.Scan(&i.PlayerID, &i.Username, &i.PasswordHash)
	return i, err
}
