// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLootAndXPToAttacker = `-- name: AddLootAndXPToAttacker :exec
UPDATE player 
SET gold_coins = gold_coins + $1, 
    elixir = elixir + $2,
    xp_points = xp_points + $3
WHERE id = $4
`

type AddLootAndXPToAttackerParams struct {
	GoldCoins int32       `json:"gold_coins"`
	Elixir    int32       `json:"elixir"`
	XpPoints  int32       `json:"xp_points"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) AddLootAndXPToAttacker(ctx context.Context, arg AddLootAndXPToAttackerParams) error {
	_, err := q.db.Exec(ctx, addLootAndXPToAttacker,
		arg.GoldCoins,
		arg.Elixir,
		arg.XpPoints,
		arg.ID,
	)
	return err
}

const deductLootAndXPFromDefender = `-- name: DeductLootAndXPFromDefender :exec
UPDATE player 
SET gold_coins = GREATEST(0, gold_coins - $1), 
    elixir = GREATEST(0, elixir - $2),
    xp_points = GREATEST(0, xp_points - $3)
WHERE id = $4
`

type DeductLootAndXPFromDefenderParams struct {
	GoldCoins int32       `json:"gold_coins"`
	Elixir    int32       `json:"elixir"`
	XpPoints  int32       `json:"xp_points"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) DeductLootAndXPFromDefender(ctx context.Context, arg DeductLootAndXPFromDefenderParams) error {
	_, err := q.db.Exec(ctx, deductLootAndXPFromDefender,
		arg.GoldCoins,
		arg.Elixir,
		arg.XpPoints,
		arg.ID,
	)
	return err
}

const deductPlayerTroops = `-- name: DeductPlayerTroops :exec
UPDATE troops_owned 
SET quantity = quantity - $1
WHERE player_id = $2 
  AND troop_type = $3
  AND current_level = $4
`

type DeductPlayerTroopsParams struct {
	Quantity     int32       `json:"quantity"`
	PlayerID     pgtype.UUID `json:"player_id"`
	TroopType    string      `json:"troop_type"`
	CurrentLevel int32       `json:"current_level"`
}

func (q *Queries) DeductPlayerTroops(ctx context.Context, arg DeductPlayerTroopsParams) error {
	_, err := q.db.Exec(ctx, deductPlayerTroops,
		arg.Quantity,
		arg.PlayerID,
		arg.TroopType,
		arg.CurrentLevel,
	)
	return err
}

const deletePlayerTroops = `-- name: DeletePlayerTroops :exec
DELETE FROM troops_owned
WHERE player_id = $1 
  AND troop_type = $2
  AND current_level = $3
`

type DeletePlayerTroopsParams struct {
	PlayerID     pgtype.UUID `json:"player_id"`
	TroopType    string      `json:"troop_type"`
	CurrentLevel int32       `json:"current_level"`
}

func (q *Queries) DeletePlayerTroops(ctx context.Context, arg DeletePlayerTroopsParams) error {
	_, err := q.db.Exec(ctx, deletePlayerTroops, arg.PlayerID, arg.TroopType, arg.CurrentLevel)
	return err
}

const getArmyCombatPower = `-- name: GetArmyCombatPower :one
WITH deployed AS (
    SELECT unnest($1::varchar[]) AS troop_type,
           unnest($2::int[]) AS troop_level,
           unnest($3::int[]) AS qty
)
SELECT 
    COALESCE(SUM((t.damage + t.hit_points) * d.qty), 0)::int AS attacker_power
FROM deployed d
JOIN troops t ON t.troop_type = d.troop_type AND t.level_req = d.troop_level
`

type GetArmyCombatPowerParams struct {
	TroopTypes []string `json:"troop_types"`
	Levels     []int32  `json:"levels"`
	Quantities []int32  `json:"quantities"`
}

func (q *Queries) GetArmyCombatPower(ctx context.Context, arg GetArmyCombatPowerParams) (int32, error) {
	row := q.db.QueryRow(ctx, getArmyCombatPower, arg.TroopTypes, arg.Levels, arg.Quantities)
	var attacker_power int32
	err := row.Scan(&attacker_power)
	return attacker_power, err
}

const getBattleByID = `-- name: GetBattleByID :one
SELECT 
    id, 
    attacker_id, 
    defender_id, 
    is_attacker_winner, 
    gold_stolen, 
    elixir_stolen, 
    damage_percentage, 
    battle_logs, 
    battle_time
FROM battles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBattleByID(ctx context.Context, id pgtype.UUID) (Battle, error) {
	row := q.db.QueryRow(ctx, getBattleByID, id)
	var i Battle
	err := row.Scan(
		&i.ID,
		&i.AttackerID,
		&i.DefenderID,
		&i.IsAttackerWinner,
		&i.GoldStolen,
		&i.ElixirStolen,
		&i.DamagePercentage,
		&i.BattleLogs,
		&i.BattleTime,
	)
	return i, err
}

const getDefenderDefensePower = `-- name: GetDefenderDefensePower :one
SELECT 
    COALESCE(SUM(b.hit_points + COALESCE(db.damage, 0)), 0)::int AS defense_power
FROM buildings_owned bo
JOIN buildings b ON bo.building_id = b.id
LEFT JOIN defense_buildings db ON b.id = db.building_id
WHERE bo.player_id = $1
`

func (q *Queries) GetDefenderDefensePower(ctx context.Context, playerID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getDefenderDefensePower, playerID)
	var defense_power int32
	err := row.Scan(&defense_power)
	return defense_power, err
}

const getOpponentVillage = `-- name: GetOpponentVillage :many
SELECT 
    bo.id AS placement_id, 
    bo.building_id, 
    bo.building_type, 
    bo.current_level, 
    bo.x_coords, 
    bo.y_coords,
    b.width,
    b.breadth
FROM buildings_owned bo
JOIN buildings b ON bo.building_id = b.id
WHERE bo.player_id = $1
`

type GetOpponentVillageRow struct {
	PlacementID  pgtype.UUID `json:"placement_id"`
	BuildingID   int32       `json:"building_id"`
	BuildingType string      `json:"building_type"`
	CurrentLevel int32       `json:"current_level"`
	XCoords      int32       `json:"x_coords"`
	YCoords      int32       `json:"y_coords"`
	Width        int32       `json:"width"`
	Breadth      int32       `json:"breadth"`
}

func (q *Queries) GetOpponentVillage(ctx context.Context, playerID pgtype.UUID) ([]GetOpponentVillageRow, error) {
	rows, err := q.db.Query(ctx, getOpponentVillage, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOpponentVillageRow
	for rows.Next() {
		var i GetOpponentVillageRow
		if err := rows.Scan(
			&i.PlacementID,
			&i.BuildingID,
			&i.BuildingType,
			&i.CurrentLevel,
			&i.XCoords,
			&i.YCoords,
			&i.Width,
			&i.Breadth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerTroopQuantity = `-- name: GetPlayerTroopQuantity :one
SELECT quantity 
FROM troops_owned 
WHERE player_id = $1 
  AND troop_type = $2
  AND current_level = $3
`

type GetPlayerTroopQuantityParams struct {
	PlayerID     pgtype.UUID `json:"player_id"`
	TroopType    string      `json:"troop_type"`
	CurrentLevel int32       `json:"current_level"`
}

func (q *Queries) GetPlayerTroopQuantity(ctx context.Context, arg GetPlayerTroopQuantityParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPlayerTroopQuantity, arg.PlayerID, arg.TroopType, arg.CurrentLevel)
	var quantity int32
	err := row.Scan(&quantity)
	return quantity, err
}

const getSuitableOpponent = `-- name: GetSuitableOpponent :one
SELECT 
    p.id AS opponent_id, 
    a.username, 
    p.village_level, 
    p.gold_coins, 
    p.elixir,
    p.xp_points
FROM player p
JOIN authorisation a ON p.id = a.player_id
WHERE p.id != $1
  AND ABS(p.village_level - $2::int) <= 1
  AND ABS(p.xp_points - $3::int) <= 500
ORDER BY RANDOM()
LIMIT 1
`

type GetSuitableOpponentParams struct {
	AttackerID   pgtype.UUID `json:"attacker_id"`
	VillageLevel int32       `json:"village_level"`
	XpPoints     int32       `json:"xp_points"`
}

type GetSuitableOpponentRow struct {
	OpponentID   pgtype.UUID `json:"opponent_id"`
	Username     string      `json:"username"`
	VillageLevel int32       `json:"village_level"`
	GoldCoins    int32       `json:"gold_coins"`
	Elixir       int32       `json:"elixir"`
	XpPoints     int32       `json:"xp_points"`
}

func (q *Queries) GetSuitableOpponent(ctx context.Context, arg GetSuitableOpponentParams) (GetSuitableOpponentRow, error) {
	row := q.db.QueryRow(ctx, getSuitableOpponent, arg.AttackerID, arg.VillageLevel, arg.XpPoints)
	var i GetSuitableOpponentRow
	err := row.Scan(
		&i.OpponentID,
		&i.Username,
		&i.VillageLevel,
		&i.GoldCoins,
		&i.Elixir,
		&i.XpPoints,
	)
	return i, err
}

const recordBattle = `-- name: RecordBattle :exec
INSERT INTO battles (
    id, 
    attacker_id, 
    defender_id, 
    is_attacker_winner, 
    gold_stolen, 
    elixir_stolen, 
    damage_percentage, 
    battle_logs 
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type RecordBattleParams struct {
	ID               pgtype.UUID    `json:"id"`
	AttackerID       pgtype.UUID    `json:"attacker_id"`
	DefenderID       pgtype.UUID    `json:"defender_id"`
	IsAttackerWinner pgtype.Bool    `json:"is_attacker_winner"`
	GoldStolen       int32          `json:"gold_stolen"`
	ElixirStolen     int32          `json:"elixir_stolen"`
	DamagePercentage pgtype.Numeric `json:"damage_percentage"`
	BattleLogs       []byte         `json:"battle_logs"`
}

func (q *Queries) RecordBattle(ctx context.Context, arg RecordBattleParams) error {
	_, err := q.db.Exec(ctx, recordBattle,
		arg.ID,
		arg.AttackerID,
		arg.DefenderID,
		arg.IsAttackerWinner,
		arg.GoldStolen,
		arg.ElixirStolen,
		arg.DamagePercentage,
		arg.BattleLogs,
	)
	return err
}
