// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buildings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedBuildingPositionInfo = `-- name: GetOwnedBuildingPositionInfo :one
SELECT bo.player_id, b.width, b.breadth
FROM buildings_owned bo
JOIN buildings b ON bo.building_id = b.id
WHERE bo.id = $1
`

type GetOwnedBuildingPositionInfoRow struct {
	PlayerID pgtype.UUID `json:"player_id"`
	Width    int32       `json:"width"`
	Breadth  int32       `json:"breadth"`
}

func (q *Queries) GetOwnedBuildingPositionInfo(ctx context.Context, id pgtype.UUID) (GetOwnedBuildingPositionInfoRow, error) {
	row := q.db.QueryRow(ctx, getOwnedBuildingPositionInfo, id)
	var i GetOwnedBuildingPositionInfoRow
	err := row.Scan(&i.PlayerID, &i.Width, &i.Breadth)
	return i, err
}

const updateBuildingPosition = `-- name: UpdateBuildingPosition :exec
UPDATE buildings_owned
SET x_coords = $2, y_coords = $3
WHERE id = $1 AND player_id = $4
`

type UpdateBuildingPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	XCoords  int32       `json:"x_coords"`
	YCoords  int32       `json:"y_coords"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) UpdateBuildingPosition(ctx context.Context, arg UpdateBuildingPositionParams) error {
	_, err := q.db.Exec(ctx, updateBuildingPosition,
		arg.ID,
		arg.XCoords,
		arg.YCoords,
		arg.PlayerID,
	)
	return err
}
