// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buildings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnedBuildingPositionInfo = `-- name: GetOwnedBuildingPositionInfo :one
SELECT bo.player_id, bo.is_built, b.width, b.breadth
FROM buildings_owned bo
JOIN buildings b ON bo.building_id = b.id
WHERE bo.id = $1
`

type GetOwnedBuildingPositionInfoRow struct {
	PlayerID pgtype.UUID `json:"player_id"`
	IsBuilt  pgtype.Bool `json:"is_built"`
	Width    int32       `json:"width"`
	Breadth  int32       `json:"breadth"`
}

func (q *Queries) GetOwnedBuildingPositionInfo(ctx context.Context, id pgtype.UUID) (GetOwnedBuildingPositionInfoRow, error) {
	row := q.db.QueryRow(ctx, getOwnedBuildingPositionInfo, id)
	var i GetOwnedBuildingPositionInfoRow
	err := row.Scan(
		&i.PlayerID,
		&i.IsBuilt,
		&i.Width,
		&i.Breadth,
	)
	return i, err
}

const getShopCatalog = `-- name: GetShopCatalog :many
SELECT id, building_type, level, name, width, breadth, cost_type, cost, hit_points, level_req FROM buildings 
WHERE level = 1
`

func (q *Queries) GetShopCatalog(ctx context.Context) ([]Building, error) {
	rows, err := q.db.Query(ctx, getShopCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Building
	for rows.Next() {
		var i Building
		if err := rows.Scan(
			&i.ID,
			&i.BuildingType,
			&i.Level,
			&i.Name,
			&i.Width,
			&i.Breadth,
			&i.CostType,
			&i.Cost,
			&i.HitPoints,
			&i.LevelReq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuildingPosition = `-- name: UpdateBuildingPosition :exec
UPDATE buildings_owned
SET x_coords = $2, y_coords = $3
WHERE id = $1 AND player_id = $4
`

type UpdateBuildingPositionParams struct {
	ID       pgtype.UUID `json:"id"`
	XCoords  int32       `json:"x_coords"`
	YCoords  int32       `json:"y_coords"`
	PlayerID pgtype.UUID `json:"player_id"`
}

func (q *Queries) UpdateBuildingPosition(ctx context.Context, arg UpdateBuildingPositionParams) error {
	_, err := q.db.Exec(ctx, updateBuildingPosition,
		arg.ID,
		arg.XCoords,
		arg.YCoords,
		arg.PlayerID,
	)
	return err
}
