// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: economy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlayerResources = `-- name: AddPlayerResources :one
UPDATE player
SET gold_coins = gold_coins + $1,
    elixir = elixir + $2
WHERE id = $3
RETURNING id, village_level, gold_coins, elixir, xp_points
`

type AddPlayerResourcesParams struct {
	GoldCoins int32       `json:"gold_coins"`
	Elixir    int32       `json:"elixir"`
	ID        pgtype.UUID `json:"id"`
}

type AddPlayerResourcesRow struct {
	ID           pgtype.UUID `json:"id"`
	VillageLevel int32       `json:"village_level"`
	GoldCoins    int32       `json:"gold_coins"`
	Elixir       int32       `json:"elixir"`
	XpPoints     int32       `json:"xp_points"`
}

func (q *Queries) AddPlayerResources(ctx context.Context, arg AddPlayerResourcesParams) (AddPlayerResourcesRow, error) {
	row := q.db.QueryRow(ctx, addPlayerResources, arg.GoldCoins, arg.Elixir, arg.ID)
	var i AddPlayerResourcesRow
	err := row.Scan(
		&i.ID,
		&i.VillageLevel,
		&i.GoldCoins,
		&i.Elixir,
		&i.XpPoints,
	)
	return i, err
}

const getResourceBuildingsForCollection = `-- name: GetResourceBuildingsForCollection :many
SELECT 
    bo.id AS owned_id,
    bo.last_collected_at,
    b.name,
    rb.resource_type,
    CAST(rb.production_rate AS float8) AS production_rate_float  --sqlc converts float8 to float64 in go
FROM buildings_owned bo
JOIN buildings b ON bo.building_id = b.id
JOIN resource_buildings rb ON b.id = rb.building_id
WHERE bo.player_id = $1
`

type GetResourceBuildingsForCollectionRow struct {
	OwnedID             pgtype.UUID      `json:"owned_id"`
	LastCollectedAt     pgtype.Timestamp `json:"last_collected_at"`
	Name                string           `json:"name"`
	ResourceType        ResourceType     `json:"resource_type"`
	ProductionRateFloat float64          `json:"production_rate_float"`
}

func (q *Queries) GetResourceBuildingsForCollection(ctx context.Context, playerID pgtype.UUID) ([]GetResourceBuildingsForCollectionRow, error) {
	rows, err := q.db.Query(ctx, getResourceBuildingsForCollection, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourceBuildingsForCollectionRow
	for rows.Next() {
		var i GetResourceBuildingsForCollectionRow
		if err := rows.Scan(
			&i.OwnedID,
			&i.LastCollectedAt,
			&i.Name,
			&i.ResourceType,
			&i.ProductionRateFloat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCollectionTime = `-- name: ResetCollectionTime :exec
UPDATE buildings_owned
SET last_collected_at = NOW()
WHERE player_id = $1 AND building_id IN (
    SELECT building_id FROM resource_buildings
)
`

func (q *Queries) ResetCollectionTime(ctx context.Context, playerID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, resetCollectionTime, playerID)
	return err
}
