// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ResourceType string

const (
	ResourceTypeGold   ResourceType = "gold"
	ResourceTypeElixir ResourceType = "elixir"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType `json:"resource_type"`
	Valid        bool         `json:"valid"` // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type ArmyCampBuilding struct {
	BuildingID      int32 `json:"building_id"`
	HousingCapacity int32 `json:"housing_capacity"`
}

type Authorisation struct {
	PlayerID     pgtype.UUID `json:"player_id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
}

type Battle struct {
	ID               pgtype.UUID      `json:"id"`
	AttackerID       pgtype.UUID      `json:"attacker_id"`
	DefenderID       pgtype.UUID      `json:"defender_id"`
	IsAttackerWinner pgtype.Bool      `json:"is_attacker_winner"`
	GoldStolen       int32            `json:"gold_stolen"`
	ElixirStolen     int32            `json:"elixir_stolen"`
	DamagePercentage pgtype.Numeric   `json:"damage_percentage"`
	BattleLogs       []byte           `json:"battle_logs"`
	BattleTime       pgtype.Timestamp `json:"battle_time"`
}

type Building struct {
	ID           int32        `json:"id"`
	BuildingType string       `json:"building_type"`
	Level        int32        `json:"level"`
	Name         string       `json:"name"`
	Width        int32        `json:"width"`
	Breadth      int32        `json:"breadth"`
	CostType     ResourceType `json:"cost_type"`
	Cost         int32        `json:"cost"`
	HitPoints    int32        `json:"hit_points"`
	LevelReq     int32        `json:"level_req"`
}

type BuildingsOwned struct {
	ID              pgtype.UUID      `json:"id"`
	PlayerID        pgtype.UUID      `json:"player_id"`
	BuildingType    string           `json:"building_type"`
	BuildingID      int32            `json:"building_id"`
	CurrentLevel    int32            `json:"current_level"`
	XCoords         int32            `json:"x_coords"`
	YCoords         int32            `json:"y_coords"`
	LastCollectedAt pgtype.Timestamp `json:"last_collected_at"`
	TimePurchased   pgtype.Timestamp `json:"time_purchased"`
	IsBuilt         pgtype.Bool      `json:"is_built"`
}

type DefenseBuilding struct {
	BuildingID  int32          `json:"building_id"`
	Damage      int32          `json:"damage"`
	AttackRange int32          `json:"attack_range"`
	AttackSpeed pgtype.Numeric `json:"attack_speed"`
	HitRate     int32          `json:"hit_rate"`
}

type Player struct {
	ID           pgtype.UUID      `json:"id"`
	VillageLevel int32            `json:"village_level"`
	GoldCoins    int32            `json:"gold_coins"`
	Elixir       int32            `json:"elixir"`
	XpPoints     int32            `json:"xp_points"`
	AttacksWon   int32            `json:"attacks_won"`
	AttacksLost  int32            `json:"attacks_lost"`
	TotalLooted  int32            `json:"total_looted"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	IsDeleted    bool             `json:"is_deleted"`
}

type ResourceBuilding struct {
	BuildingID     int32          `json:"building_id"`
	ProductionRate pgtype.Numeric `json:"production_rate"`
	ResourceType   ResourceType   `json:"resource_type"`
}

type StorageBuilding struct {
	BuildingID      int32        `json:"building_id"`
	StorageCapacity int32        `json:"storage_capacity"`
	ResourceType    ResourceType `json:"resource_type"`
}

type Troop struct {
	TroopType    string      `json:"troop_type"`
	LevelReq     int32       `json:"level_req"`
	ElixirCost   int32       `json:"elixir_cost"`
	HitPoints    int32       `json:"hit_points"`
	HitRate      int32       `json:"hit_rate"`
	Damage       int32       `json:"damage"`
	Speed        int32       `json:"speed"`
	AttackRange  int32       `json:"attack_range"`
	HousingSpace int32       `json:"housing_space"`
	Description  pgtype.Text `json:"description"`
}

type TroopsOwned struct {
	PlayerID     pgtype.UUID `json:"player_id"`
	TroopType    string      `json:"troop_type"`
	CurrentLevel int32       `json:"current_level"`
	Quantity     int32       `json:"quantity"`
}
