// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ResourceType string

const (
	ResourceTypeGold   ResourceType = "gold"
	ResourceTypeElixir ResourceType = "elixir"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType
	Valid        bool // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type ArmyCampBuilding struct {
	BuildingID      int32
	HousingCapacity int32
}

type Authorisation struct {
	PlayerID     uuid.UUID
	Username     string
	PasswordHash string
}

type Battle struct {
	ID               uuid.UUID
	AttackerID       uuid.UUID
	DefenderID       uuid.UUID
	IsAttackerWinner sql.NullBool
	GoldStolen       int32
	ElixirStolen     int32
	DamagePercentage string
	BattleLogs       pqtype.NullRawMessage
	BattleTime       time.Time
}

type Building struct {
	ID           int32
	BuildingType string
	Level        int32
	Name         string
	Width        int32
	Breadth      int32
	CostType     ResourceType
	Cost         int32
	HitPoints    int32
	LevelReq     int32
}

type BuildingsOwned struct {
	ID              uuid.UUID
	PlayerID        uuid.UUID
	BuildingType    string
	BuildingID      int32
	CurrentLevel    int32
	XCoords         int32
	YCoords         int32
	LastCollectedAt sql.NullTime
	TimePurchased   sql.NullTime
	IsBuilt         sql.NullBool
}

type DefenseBuilding struct {
	BuildingID  int32
	Damage      int32
	AttackRange int32
	AttackSpeed string
	HitRate     int32
}

type Player struct {
	ID           uuid.UUID
	VillageLevel int32
	GoldCoins    int32
	Elixir       int32
	XpPoints     int32
	AttacksWon   int32
	AttacksLost  int32
	TotalLooted  int32
	CreatedAt    time.Time
	IsDeleted    bool
}

type ResourceBuilding struct {
	BuildingID     int32
	ProductionRate string
	ResourceType   ResourceType
}

type StorageBuilding struct {
	BuildingID      int32
	StorageCapacity int32
	ResourceType    ResourceType
}

type Troop struct {
	TroopType    string
	LevelReq     int32
	ElixirCost   int32
	HitPoints    int32
	HitRate      int32
	Damage       int32
	Speed        int32
	AttackRange  int32
	HousingSpace int32
	Description  sql.NullString
}

type TroopsOwned struct {
	PlayerID     uuid.UUID
	TroopType    string
	CurrentLevel int32
	Quantity     int32
}
