// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardData = `-- name: GetDashboardData :many
SELECT 
    a.username, 
    p.gold_coins, 
    p.elixir, 
    p.village_level, 
    p.xp_points,
    bo.id AS placement_id,
    bo.building_id,
    bo.building_type,
    bo.current_level,
    bo.x_coords,
    bo.y_coords,
    bo.is_built
FROM player p
JOIN authorisation a ON p.id = a.player_id
LEFT JOIN buildings_owned bo ON p.id = bo.player_id
WHERE p.id = $1
`

type GetDashboardDataRow struct {
	Username     string      `json:"username"`
	GoldCoins    int32       `json:"gold_coins"`
	Elixir       int32       `json:"elixir"`
	VillageLevel int32       `json:"village_level"`
	XpPoints     int32       `json:"xp_points"`
	PlacementID  pgtype.UUID `json:"placement_id"`
	BuildingID   pgtype.Int4 `json:"building_id"`
	BuildingType pgtype.Text `json:"building_type"`
	CurrentLevel pgtype.Int4 `json:"current_level"`
	XCoords      pgtype.Int4 `json:"x_coords"`
	YCoords      pgtype.Int4 `json:"y_coords"`
	IsBuilt      pgtype.Bool `json:"is_built"`
}

func (q *Queries) GetDashboardData(ctx context.Context, id pgtype.UUID) ([]GetDashboardDataRow, error) {
	rows, err := q.db.Query(ctx, getDashboardData, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDashboardDataRow
	for rows.Next() {
		var i GetDashboardDataRow
		if err := rows.Scan(
			&i.Username,
			&i.GoldCoins,
			&i.Elixir,
			&i.VillageLevel,
			&i.XpPoints,
			&i.PlacementID,
			&i.BuildingID,
			&i.BuildingType,
			&i.CurrentLevel,
			&i.XCoords,
			&i.YCoords,
			&i.IsBuilt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
