// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upgrade.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitBuildingUpgrade = `-- name: CommitBuildingUpgrade :exec
UPDATE buildings_owned
SET building_id = $1, current_level = $2
WHERE id = $3
`

type CommitBuildingUpgradeParams struct {
	BuildingID   int32       `json:"building_id"`
	CurrentLevel int32       `json:"current_level"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) CommitBuildingUpgrade(ctx context.Context, arg CommitBuildingUpgradeParams) error {
	_, err := q.db.Exec(ctx, commitBuildingUpgrade, arg.BuildingID, arg.CurrentLevel, arg.ID)
	return err
}

const getNextLevelBuilding = `-- name: GetNextLevelBuilding :one
SELECT 
    id AS next_building_id, 
    cost AS build_cost, 
    cost_type, 
    level_req,
    name
FROM buildings
WHERE building_type = $1 AND level = $2
`

type GetNextLevelBuildingParams struct {
	BuildingType string `json:"building_type"`
	Level        int32  `json:"level"`
}

type GetNextLevelBuildingRow struct {
	NextBuildingID int32        `json:"next_building_id"`
	BuildCost      int32        `json:"build_cost"`
	CostType       ResourceType `json:"cost_type"`
	LevelReq       int32        `json:"level_req"`
	Name           string       `json:"name"`
}

func (q *Queries) GetNextLevelBuilding(ctx context.Context, arg GetNextLevelBuildingParams) (GetNextLevelBuildingRow, error) {
	row := q.db.QueryRow(ctx, getNextLevelBuilding, arg.BuildingType, arg.Level)
	var i GetNextLevelBuildingRow
	err := row.Scan(
		&i.NextBuildingID,
		&i.BuildCost,
		&i.CostType,
		&i.LevelReq,
		&i.Name,
	)
	return i, err
}

const getOwnedBuildingDetails = `-- name: GetOwnedBuildingDetails :one
SELECT 
    bo.id AS placement_id, 
    bo.current_level, 
    b.building_type 
FROM buildings_owned bo
JOIN buildings b ON bo.building_id = b.id
WHERE bo.id = $1 AND bo.player_id = $2
`

type GetOwnedBuildingDetailsParams struct {
	ID       pgtype.UUID `json:"id"`
	PlayerID pgtype.UUID `json:"player_id"`
}

type GetOwnedBuildingDetailsRow struct {
	PlacementID  pgtype.UUID `json:"placement_id"`
	CurrentLevel int32       `json:"current_level"`
	BuildingType string      `json:"building_type"`
}

func (q *Queries) GetOwnedBuildingDetails(ctx context.Context, arg GetOwnedBuildingDetailsParams) (GetOwnedBuildingDetailsRow, error) {
	row := q.db.QueryRow(ctx, getOwnedBuildingDetails, arg.ID, arg.PlayerID)
	var i GetOwnedBuildingDetailsRow
	err := row.Scan(&i.PlacementID, &i.CurrentLevel, &i.BuildingType)
	return i, err
}

const payForUpgrade = `-- name: PayForUpgrade :exec
UPDATE player
SET gold_coins = gold_coins - $1,
    elixir = elixir - $2
WHERE id = $3
`

type PayForUpgradeParams struct {
	GoldCoins int32       `json:"gold_coins"`
	Elixir    int32       `json:"elixir"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) PayForUpgrade(ctx context.Context, arg PayForUpgradeParams) error {
	_, err := q.db.Exec(ctx, payForUpgrade, arg.GoldCoins, arg.Elixir, arg.ID)
	return err
}
