// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: village.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlayerBuildings = `-- name: GetPlayerBuildings :many
SELECT id, player_id, building_type, building_id, current_level, x_coords, y_coords, last_collected_at, time_purchased, is_built FROM "buildings_owned"
WHERE player_id = $1
`

func (q *Queries) GetPlayerBuildings(ctx context.Context, playerID pgtype.UUID) ([]BuildingsOwned, error) {
	rows, err := q.db.Query(ctx, getPlayerBuildings, playerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildingsOwned
	for rows.Next() {
		var i BuildingsOwned
		if err := rows.Scan(
			&i.ID,
			&i.PlayerID,
			&i.BuildingType,
			&i.BuildingID,
			&i.CurrentLevel,
			&i.XCoords,
			&i.YCoords,
			&i.LastCollectedAt,
			&i.TimePurchased,
			&i.IsBuilt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerProfile = `-- name: GetPlayerProfile :one
SELECT id, village_level, gold_coins, elixir, xp_points, attacks_won, attacks_lost, total_looted, created_at, is_deleted FROM "player"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlayerProfile(ctx context.Context, id pgtype.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerProfile, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.VillageLevel,
		&i.GoldCoins,
		&i.Elixir,
		&i.XpPoints,
		&i.AttacksWon,
		&i.AttacksLost,
		&i.TotalLooted,
		&i.CreatedAt,
		&i.IsDeleted,
	)
	return i, err
}
